def summarize_results(output_dir):
    lines = []

    lines.append(title("jbrown1618"))
    lines.append("")
    lines.append(byline())

    with open(f"{output_dir}/README.md", "w") as f:
        f.write("\n".join(lines))


def title(user):
    return f"# Spotify Summary for {user}"


def byline():
    return "Generated by [jbrown1618/spotify-stats](https://github.com/jbrown1618/spotify-stats)"